### PR TITLE
Added estimates by Sun and He (ISMIR 2021).

### PR DESCRIPTION
**Pull request by Koko-Son**
Added estimates by  "Xiaoheng Sun, Qiqi He, Yongwei Gao, Wei Li. Musical Tempo Estimation Using a Multi-scale Network. in Proc. of the 22nd Int. Society for Music Information Retrieval Conf., Online, 2021".

### CODE REVIEW

**Comment by hendriks73** [comment]
Thank you for your PR. I will review this as soon as possible!

**Comment by hendriks73** [comment]
I have merged your data, but have found the following two issues:

### Bad folder structure/wrong file names

The ballroom estimates do not follow the folder structure of the other estimates in the repo. Using the same folder structure is essential though for `tempo_eval` to work properly. I will fix this. Also, some file names were wrong, but fixable.

The same is true for the GTzan estimates. File names didn't follow the `tempo_eval` conventions. I will fix those as well.

### Missing estimates for GiantSteps Tempo
```
WARNING  Failed to find item '1327052.LOFI.jams' in estimates by 'sun2021/default'.
WARNING  Failed to find item '3041383.LOFI.jams' in estimates by 'sun2021/default'.
WARNING  Failed to find item '3041381.LOFI.jams' in estimates by 'sun2021/default'.
```

Any chance you have these estimates?
If you need access to these files, you can download them from here:

- https://www.beatunes.com/download/1327052.LOFI.mp3
- https://www.beatunes.com/download/3041383.LOFI.mp3
- https://www.beatunes.com/download/3041381.LOFI.mp3

**Comment by hendriks73** [comment]
@Koko-Son Any chance you can provide the three missing estimates soon? I would really appreciate it.

**Comment by hendriks73** [comment]
@Koko-Son Just FYI: I'm going to generate a new eval report with your results tomorrow (European time).

**Comment by Koko-Son** [comment]
@hendriks73 Sorry for my late reply. Attached are the estimates. We have also sent the files via e-mail.
[estimates.zip](https://github.com/tempoeval/tempo_eval/files/9003050/estimates.zip)

**Comment by hendriks73** [comment]
**Thanks so much!**
I'm working on getting those values in there and publishing it right now.
Also - I'm probably going to tweet about it. Would you like me to mention your twitter handle? If so, what is it?

**Comment by Koko-Son** [comment]
@hendriks73 Thanks for your kindness! But I don't have a twitter account, so it's OK. We are looking forward to seeing your report!

**Pull request merged**
